title: Turbow Farms - Fresh Cut Flowers
baseurl: /
permalink: '/:title/'
palette: blue
header:
  has_nav: true
  logo_img: /images/t_edited.webp
  menu:
    actions:
      - label: Sign Up
        url: /signup
  title: Turbow Farms
footer:
  content: '&copy; Turbow Farms. All rights reserved.'
  has_nav: true
  has_social: true
  has_subscribe: true
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
  logo_img: /images/t_edited.webp
  nav_title: Company
  social_title: Community
  subscribe_content: Stay up to date with our latest developments.
  subscribe_title: Subscribe
  tagline: 'Turbow Farms - 23263 Mora Glen Drive, Los Altos, CA 94024'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
